apiVersion: apps/v1
kind: Deployment
metadata:
  name: avatar
  labels:
    app: avatar
spec:
  selector:
    matchLabels:
      app: avatar
  replicas: 1
  template:
    metadata:
      labels:
        app: avatar
    spec:
      containers:
      - name: avatar
        image: svennam92/avatar:v1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3005
          name: http
